# Convolution and Feature Extraction

## Learning Objectives
- Understand the convolution operation and its role in CNNs.
- Learn how convolutions extract local features from images.

## Introduction
Convolutional Neural Networks (CNN) is a powerful family of neural networks chiefly for manipulating image data. Convolution layers apply filters to input images to extract important features like edges, textures, and shapes. This forms the fundamental building block of convolutional neural networks.

## Core Concepts
- **Convolution:** Sliding a filter (kernel) over input to produce feature maps.
- **Filters:** Small matrices that detect specific patterns.
- **Stride and Padding:** Control the movement of filters and output size.
- **Feature Maps:** Outputs of convolution layers capturing detected features.

## Example
Manual convolution operation on a small image patch.

In [1]:
import numpy as np

# Sample 5x5 grayscale image
image = np.array([
    [1, 2, 0, 2, 1],
    [3, 1, 2, 0, 0],
    [0, 1, 3, 1, 2],
    [2, 0, 1, 3, 1],
    [1, 2, 0, 0, 2]
])

# Sample 3x3 filter (edge detection)
filter = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

def convolve2d(image, filter):
    filter_size = filter.shape[0]
    output_dim = image.shape[0] - filter_size + 1
    output = np.zeros((output_dim, output_dim))
    for i in range(output_dim):
        for j in range(output_dim):
            patch = image[i:i+filter_size, j:j+filter_size]
            output[i, j] = np.sum(patch * filter)
    return output

feature_map = convolve2d(image, filter)
print("Feature Map:")
print(feature_map)

Feature Map:
[[-1.  1.  2.]
 [-1. -2.  3.]
 [-1. -1. -1.]]


3D Convolution

In [5]:
import numpy as np

def convolve3d(image, filter):
    # get the size of the input image and kernel
    (image_height, image_width, image_channels) = image.shape
    (kernel_height, kernel_width, kernel_channels) = filter.shape
    
    # calculate the padding needed for 'same' convolution
    pad_h = (kernel_height - 1) // 2
    pad_w = (kernel_width - 1) // 2
    
    # pad the input image with zeros
    padded_image = np.pad(image, ((pad_h, pad_h), (pad_w, pad_w), (0, 0)), 'constant')
    
    # create an empty output tensor
    output_height = image_height
    output_width = image_width
    output_channels = kernel_channels
    output = np.zeros((output_height, output_width, output_channels))
    
    # perform the convolution operation
    for i in range(output_height):
        for j in range(output_width):
            for k in range(output_channels):
                output[i, j, k] = np.sum(filter[:, :, k] * padded_image[i:i+kernel_height, j:j+kernel_width, :])
    
    return output


In [6]:
# create an example image and kernel
image = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
filter = np.array([[[1, 0], [0, -1]], [[0, 1], [-1, 0]]])

# perform the convolution operation
output = convolve3d(image, filter)

print('Input image:')
print(image)

print('\nKernel:')
print(filter)

print('\nOutput:')
print(output)


Input image:
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

Kernel:
[[[ 1  0]
  [ 0 -1]]

 [[ 0  1]
  [-1  0]]]

Output:
[[[-6.  2.]
  [-2. -2.]]

 [[-6.  2.]
  [-2. -2.]]

 [[-3.  1.]
  [-1. -1.]]]


## Exercise
Try different filters such as a sharpening or blur filter and observe the output feature maps.

In [ ]:
# Your code here

## Summary
- Convolution extracts crucial features by applying localized filters.
- Understanding convolution helps in designing CNN architectures.


## Further Reading
- [CS231n Convolutional Neural Networks](http://cs231n.github.io/convolutional-networks/)
- [Introduction to Convolution](https://www.analyticsvidhya.com/blog/2018/12/introduction-convolutional-neural-networks-cnn/)
