# Self-Attention Mechanism

## Learning Objectives
- Understand the concept of self-attention in sequence models.
- Learn how self-attention computes relationships between elements in a sequence.

## Introduction
Self-attention allows models to weigh the importance of different elements in a sequence when encoding information, crucial to Transformer architectures.

## Core Concepts
- **Query, Key, Value vectors:** Learned representations for attention.
- **Attention scores:** Compute similarity between queries and keys.
- **Softmax:** Normalize scores to weights.
- **Weighted sum:** Combine values using attention weights.

## Example
Manual computation of self-attention scores.

In [1]:
import numpy as np

# Sample input matrix (3 tokens, embedding size 4)
X = np.array([
    [1, 0, 1, 0],
    [0, 2, 0, 2],
    [1, 1, 1, 1]
])

# Define Query, Key, Value matrices
W_q = np.eye(4)
W_k = np.eye(4)
W_v = np.eye(4)

Q = X.dot(W_q)
K = X.dot(W_k)
V = X.dot(W_v)

# Compute attention scores
scores = Q.dot(K.T) / np.sqrt(Q.shape[1])
print("Attention Scores:\n", scores)

# Softmax
exp_scores = np.exp(scores - np.max(scores, axis=1, keepdims=True))
attention_weights = exp_scores / exp_scores.sum(axis=1, keepdims=True)
print("\nAttention Weights:\n", attention_weights)

# Weighted sum output
output = attention_weights.dot(V)
print("\nSelf-Attention Output:\n", output)

Attention Scores:
 [[1. 0. 1.]
 [0. 4. 2.]
 [1. 2. 2.]]

Attention Weights:
 [[0.4223188  0.1553624  0.4223188 ]
 [0.01587624 0.86681333 0.11731043]
 [0.1553624  0.4223188  0.4223188 ]]

Self-Attention Output:
 [[0.8446376  0.73304361 0.8446376  0.73304361]
 [0.13318667 1.85093709 0.13318667 1.85093709]
 [0.5776812  1.26695639 0.5776812  1.26695639]]


## Exercise
Try changing the input values and observe the changes in attention weights.

In [ ]:
# Your code here

## Summary
- Self-attention computes contextual relationships between sequence elements.
- It enables models to dynamically weight input features for improved learning.


## Further Reading
- [The Illustrated Transformer](http://jalammar.github.io/illustrated-transformer/)
- [Attention Is All You Need (Vaswani et al., 2017)](https://arxiv.org/abs/1706.03762)
